/**
 * 报告生成器 — JSON + Markdown + HTML
 */

import * as fs from "fs";
import * as path from "path";
import type { HarnessResult, DeltaResult, ReportData } from "../types.js";

// ====== JSON ======

export function saveJson(outputDir: string, runId: string, result: HarnessResult): string {
  const dir = path.resolve(outputDir);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const p = path.join(dir, `${runId}.json`);
  fs.writeFileSync(p, JSON.stringify(result, null, 2), "utf-8");
  return p;
}

// ====== Markdown ======

export function generateMarkdown(data: ReportData): string {
  const { result, deltas } = data;
  const lines: string[] = [];

  lines.push(`# 🏃 Harness Report — ${result.runId}`);
  lines.push("");
  lines.push(`| 字段 | 值 |`);
  lines.push(`|------|-----|`);
  lines.push(`| Run ID | \`${result.runId}\` |`);
  lines.push(`| Timestamp | ${result.timestamp} |`);
  lines.push(`| Mode | ${result.config.mode} |`);
  lines.push(`| Models | ${result.config.models.join(", ")} |`);
  lines.push(`| Total Duration | ${result.totalDurationMs}ms |`);
  lines.push(`| Cases | ${result.evaluated.length} |`);
  lines.push("");

  // Summaries
  lines.push(`## Model Summaries`);
  lines.push("");
  lines.push(`| Model | Matrix | Total | Passed | Failed | Rate | AvgScore | AvgDuration |`);
  lines.push(`|-------|--------|-------|--------|--------|------|----------|-------------|`);
  for (const s of result.summaries) {
    lines.push(`| ${s.model} | ${s.matrixName || "-"} | ${s.total} | ${s.passed} | ${s.failed} | ${s.passRate}% | ${s.avgScore} | ${s.avgDurationMs}ms |`);
  }
  lines.push("");

  // Category breakdown
  lines.push(`## Category Breakdown`);
  lines.push("");
  for (const s of result.summaries) {
    lines.push(`### ${s.model}${s.matrixName ? ` (${s.matrixName})` : ""}`);
    lines.push("");
    lines.push(`| Category | Total | Passed | Rate | AvgScore |`);
    lines.push(`|----------|-------|--------|------|----------|`);
    for (const [cat, d] of Object.entries(s.categoryBreakdown)) {
      lines.push(`| ${cat} | ${d.total} | ${d.passed} | ${Math.round((d.passed / d.total) * 100)}% | ${d.avgScore} |`);
    }
    lines.push("");
  }

  // Evaluator breakdown
  lines.push(`## Evaluator Breakdown`);
  lines.push("");
  for (const s of result.summaries) {
    lines.push(`### ${s.model}`);
    lines.push("");
    lines.push(`| Evaluator | Total | Passed | Rate | AvgScore |`);
    lines.push(`|-----------|-------|--------|------|----------|`);
    for (const [name, d] of Object.entries(s.evaluatorBreakdown)) {
      lines.push(`| ${name} | ${d.total} | ${d.passed} | ${Math.round((d.passed / d.total) * 100)}% | ${d.avgScore} |`);
    }
    lines.push("");
  }

  // Deltas
  if (deltas && deltas.length > 0) {
    lines.push(`## Delta (vs Baseline)`);
    lines.push("");
    lines.push(`| Case | Model | Baseline | Current | Delta | Status |`);
    lines.push(`|------|-------|----------|---------|-------|--------|`);
    for (const d of deltas) {
      const icon = d.status === "improved" ? "🟢" : d.status === "regressed" ? "🔴" : d.status === "new-pass" ? "🆕✅" : d.status === "new-fail" ? "🆕❌" : "⚪";
      lines.push(`| ${d.caseId} | ${d.model} | ${d.baselineScore} | ${d.currentScore} | ${d.scoreDelta > 0 ? "+" : ""}${d.scoreDelta} | ${icon} ${d.status} |`);
    }
    lines.push("");
  }

  // Failed details
  const failed = result.evaluated.filter((e) => !e.passed);
  if (failed.length > 0) {
    lines.push(`## Failed Cases (${failed.length})`);
    lines.push("");
    for (const e of failed) {
      lines.push(`### ${e.run.caseId} — ${e.run.caseName} [${e.run.category}]`);
      lines.push("");
      lines.push(`- **Model**: ${e.run.model}${e.run.matrixName ? ` / ${e.run.matrixName}` : ""}`);
      lines.push(`- **Score**: ${e.totalScore} / 100`);
      lines.push(`- **Duration**: ${e.run.durationMs}ms (${e.run.iterations} iterations)`);
      lines.push(`- **Answer**:`);
      lines.push(`\`\`\``);
      lines.push(e.run.answer || "(empty)");
      lines.push(`\`\`\``);
      lines.push("");
      for (const s of e.scores) {
        if (!s.passed) {
          lines.push(`**${s.evaluator}** (${s.score}pts):`);
          for (const f of s.failures) {
            lines.push(`- ${f}`);
          }
          lines.push("");
        }
      }
    }
  }

  lines.push(`---`);
  lines.push(`*Generated by RunCoach Harness v2*`);
  return lines.join("\n");
}

export function saveMarkdown(outputDir: string, runId: string, data: ReportData): string {
  const dir = path.resolve(outputDir);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const p = path.join(dir, `${runId}.md`);
  fs.writeFileSync(p, generateMarkdown(data), "utf-8");
  return p;
}

// ====== HTML ======

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function generateTurnDetails(turns: { turnIndex: number; input: string; answer: string; toolCalls: { tool: string; durationMs: number; error?: string }[]; iterations: number; durationMs: number }[]): string {
  return `<div class="detail-section"><strong>MULTI-TURN (${turns.length} turns):</strong>` + 
    turns.map((t, idx) => `
      <div style="margin:8px 0;padding:8px;border:1px solid var(--border);border-left:3px solid var(--accent);">
        <div><strong>Turn ${idx + 1}:</strong> ${escapeHtml(t.input)}</div>
        <div style="color:var(--muted);font-size:14px;margin-top:4px;">
          ${t.durationMs}ms · ${t.iterations} iter · tools: ${t.toolCalls.map((tc) => tc.tool).join(", ") || "none"}
        </div>
        <pre style="margin-top:6px;">${escapeHtml(t.answer.slice(0, 300))}</pre>
      </div>
    `).join("") + "</div>";
}

export function generateHtml(data: ReportData): string {
  const { result, deltas } = data;

  const total = result.evaluated.length;
  const passed = result.evaluated.filter((e) => e.passed).length;
  const failed = total - passed;
  const passRate = Math.round((passed / total) * 100);

  // 数据
  const cases = result.evaluated.map((e) => ({
    id: e.run.caseId,
    name: e.run.caseName,
    category: e.run.category,
    model: e.run.model,
    passed: e.passed,
    score: e.totalScore,
    duration: e.run.durationMs,
    iterations: e.run.iterations,
    answer: e.run.answer,
    failures: e.scores.filter((s) => !s.passed).flatMap((s) => s.failures),
    tools: e.run.toolCalls.map((t) => t.tool),
    isMultiTurn: !!e.run.turnResults && e.run.turnResults.length > 0,
    turnResults: e.run.turnResults || [],
  }));

  const rows = cases
    .map(
      (c, i) => `
    <tr class="case-row ${c.passed ? "passed" : "failed"}" data-category="${c.category}" data-model="${c.model}" data-passed="${c.passed}" onclick="toggleDetail(${i})">
      <td>${c.id}${c.isMultiTurn ? ' <span class="tag" style="border-color:var(--accent);color:var(--accent)">M</span>' : ""}</td>
      <td>${c.name}</td>
      <td><span class="tag">${c.category}</span></td>
      <td>${c.model}</td>
      <td class="status">${c.passed ? "✅" : "❌"}</td>
      <td class="score">${c.score}</td>
      <td>${c.duration}ms</td>
      <td>${c.iterations}</td>
    </tr>
    <tr class="detail-row" id="detail-${i}" style="display:none">
      <td colspan="8">
        <div class="detail">
          <div class="detail-section">
            <strong>ANSWER:</strong>
            <pre>${escapeHtml(c.answer.slice(0, 500))}</pre>
          </div>
          ${c.failures.length > 0 ? `<div class="detail-section"><strong>FAILURES:</strong><ul>${c.failures.map((f) => `<li>${escapeHtml(f)}</li>`).join("")}</ul></div>` : ""}
          ${c.tools.length > 0 ? `<div class="detail-section"><strong>TOOLS:</strong> ${c.tools.join(", ")}</div>` : ""}
          ${c.isMultiTurn ? generateTurnDetails(c.turnResults) : ""}
        </div>
      </td>
    </tr>`
    )
    .join("");

  const categories = [...new Set(cases.map((c) => c.category))];
  const categoryFilters = categories.map((cat) =>
    `<button class="filter-btn" data-filter="${cat}" onclick="filterCategory('${cat}')">${cat}</button>`
  ).join(" ");

  const deltaRows = deltas
    ? deltas
        .map(
          (d) => `
    <tr class="${d.status}">
      <td>${d.caseId}</td>
      <td>${d.model}</td>
      <td>${d.baselineScore}</td>
      <td class="score">${d.currentScore}</td>
      <td class="delta ${d.scoreDelta >= 0 ? "up" : "down"}">${d.scoreDelta > 0 ? "+" : ""}${d.scoreDelta}</td>
      <td><span class="tag ${d.status}">${d.status}</span></td>
    </tr>`
        )
        .join("")
    : '<tr><td colspan="6" class="empty">No baseline comparison</td></tr>';

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Harness // ${result.runId}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=VT323&display=swap');

  :root {
    --bg: #18181b;
    --fg: #e4e4e7;
    --muted: #71717a;
    --accent: #f97316;
    --accent-dim: #c2410c;
    --pass: #22c55e;
    --fail: #ef4444;
    --card: #27272a;
    --border: #3f3f46;
  }

  * { box-sizing: border-box; }
  body {
    margin: 0;
    padding: 40px 20px;
    background: var(--bg);
    color: var(--fg);
    font-family: 'VT323', monospace;
    font-size: 18px;
    line-height: 1.5;
  }

  .crt-overlay {
    position: fixed;
    top: 0; left: 0; right: 0; bottom: 0;
    pointer-events: none;
    background: repeating-linear-gradient(
      0deg,
      rgba(0,0,0,0.08) 0px,
      rgba(0,0,0,0.08) 1px,
      transparent 1px,
      transparent 2px
    );
    z-index: 9999;
  }

  .container {
    max-width: 1200px;
    margin: 0 auto;
  }

  h1 {
    font-size: 48px;
    margin: 0 0 8px 0;
    color: var(--accent);
    text-shadow: 2px 2px 0 var(--accent-dim);
    letter-spacing: 2px;
  }

  .meta {
    color: var(--muted);
    font-size: 16px;
    margin-bottom: 30px;
    border-bottom: 2px solid var(--border);
    padding-bottom: 15px;
  }

  .summary {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 16px;
    margin-bottom: 40px;
  }
  .card {
    background: var(--card);
    border: 2px solid var(--border);
    padding: 20px;
    text-align: center;
    position: relative;
  }
  .card::before {
    content: "";
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 3px;
    background: var(--accent);
  }
  .card .value {
    font-size: 48px;
    font-weight: 400;
    color: var(--fg);
  }
  .card .label {
    font-size: 16px;
    color: var(--muted);
    margin-top: 4px;
    text-transform: uppercase;
    letter-spacing: 1px;
  }
  .card.pass .value { color: var(--pass); }
  .card.fail .value { color: var(--fail); }

  .filters {
    margin-bottom: 20px;
  }
  .filters button {
    font-family: 'VT323', monospace;
    font-size: 16px;
    background: var(--card);
    border: 1px solid var(--border);
    color: var(--fg);
    padding: 6px 14px;
    margin: 0 4px 4px 0;
    cursor: pointer;
    text-transform: uppercase;
  }
  .filters button:hover {
    border-color: var(--accent);
    color: var(--accent);
  }
  .filters button.active {
    background: var(--accent);
    color: var(--bg);
    border-color: var(--accent);
  }

  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 16px;
    margin-top: 10px;
  }
  th {
    background: var(--card);
    padding: 12px;
    text-align: left;
    font-weight: 400;
    color: var(--accent);
    border-bottom: 2px solid var(--accent);
    text-transform: uppercase;
    letter-spacing: 1px;
  }
  td {
    padding: 10px 12px;
    border-bottom: 1px solid var(--border);
    vertical-align: top;
  }
  tr.case-row:hover { background: rgba(249, 115, 22, 0.05); cursor: pointer; }
  tr.case-row.passed .status { color: var(--pass); }
  tr.case-row.failed .status { color: var(--fail); }
  tr.case-row.failed { background: rgba(239, 68, 68, 0.05); }
  tr.hidden { display: none; }

  .detail-row td { padding: 0; border: none; }
  .detail {
    background: #1e1e22;
    border: 1px solid var(--border);
    border-left: 3px solid var(--accent);
    padding: 16px;
    margin: 8px 12px;
  }
  .detail-section {
    margin-bottom: 12px;
  }
  .detail-section pre {
    background: var(--card);
    padding: 10px;
    border: 1px solid var(--border);
    font-family: 'VT323', monospace;
    font-size: 14px;
    overflow: auto;
    max-height: 200px;
    white-space: pre-wrap;
  }
  .detail-section ul {
    margin: 4px 0;
    padding-left: 20px;
  }
  .detail-section li {
    color: var(--fail);
  }

  .tag {
    display: inline-block;
    padding: 2px 8px;
    background: var(--card);
    border: 1px solid var(--border);
    font-size: 14px;
  }
  .tag.improved { border-color: var(--pass); color: var(--pass); }
  .tag.regressed { border-color: var(--fail); color: var(--fail); }
  .tag.new-pass { border-color: var(--pass); color: var(--pass); }
  .tag.new-fail { border-color: var(--fail); color: var(--fail); }

  .score { color: var(--accent); font-weight: bold; }
  .delta.up { color: var(--pass); }
  .delta.down { color: var(--fail); }
  .empty { color: var(--muted); text-align: center; }

  .section { margin-top: 50px; }
  .section h2 {
    font-size: 28px;
    color: var(--accent);
    border-bottom: 2px solid var(--border);
    padding-bottom: 8px;
    text-transform: uppercase;
    letter-spacing: 2px;
  }
  .glitch {
    animation: glitch 1s linear infinite;
  }
  @keyframes glitch {
    2%, 64% { transform: translate(2px,0) skew(0deg); }
    4%, 60% { transform: translate(-2px,0) skew(0deg); }
    62% { transform: translate(0,0) skew(5deg); }
  }
  footer {
    margin-top: 60px;
    padding-top: 20px;
    border-top: 2px solid var(--border);
    color: var(--muted);
    font-size: 14px;
    text-align: center;
  }
</style>
</head>
<body>
<div class="crt-overlay"></div>
<div class="container">
  <h1 class="glitch">// HARNESS REPORT</h1>
  <div class="meta">
    RUN_ID: ${result.runId} // ${result.timestamp} // MODE: ${result.config.mode} // MODELS: ${result.config.models.join(", ")}
  </div>

  <div class="summary">
    <div class="card pass">
      <div class="value">${passed}</div>
      <div class="label">PASSED</div>
    </div>
    <div class="card fail">
      <div class="value">${failed}</div>
      <div class="label">FAILED</div>
    </div>
    <div class="card">
      <div class="value">${passRate}%</div>
      <div class="label">PASS RATE</div>
    </div>
    <div class="card">
      <div class="value">${result.totalDurationMs}ms</div>
      <div class="label">DURATION</div>
    </div>
  </div>

  <div class="section">
    <h2>> ALL CASES</h2>
    <div class="filters">
      <button class="filter-btn active" data-filter="all" onclick="filterAll()">ALL</button>
      <button class="filter-btn" onclick="filterPass(true)">PASS</button>
      <button class="filter-btn" onclick="filterPass(false)">FAIL</button>
      ${categoryFilters}
    </div>
    <table>
      <tr><th>ID</th><th>NAME</th><th>CATEGORY</th><th>MODEL</th><th>STATUS</th><th>SCORE</th><th>DURATION</th><th>ITERATIONS</th></tr>
      ${rows}
    </table>
  </div>

  <div class="section">
    <h2>> DELTA COMPARISON</h2>
    <table>
      <tr><th>CASE</th><th>MODEL</th><th>BASELINE</th><th>CURRENT</th><th>DELTA</th><th>STATUS</th></tr>
      ${deltaRows}
    </table>
  </div>

  <footer>
    RUNCOACH HARNESS v2 // GENERATED ${new Date().toISOString().slice(0, 19)}
  </footer>
</div>

<script>
function toggleDetail(i) {
  const row = document.getElementById('detail-' + i);
  if (!row) return;
  row.style.display = row.style.display === 'none' ? 'table-row' : 'none';
}
function filterAll() {
  document.querySelectorAll('.case-row').forEach(r => r.classList.remove('hidden'));
  document.querySelectorAll('.detail-row').forEach(r => r.classList.add('hidden'));
  document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
  document.querySelector('button[data-filter="all"]').classList.add('active');
}
function filterPass(passed) {
  document.querySelectorAll('.case-row').forEach(r => {
    if (r.dataset.passed === String(passed)) r.classList.remove('hidden');
    else r.classList.add('hidden');
  });
  document.querySelectorAll('.detail-row').forEach(r => r.classList.add('hidden'));
  document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
}
function filterCategory(cat) {
  document.querySelectorAll('.case-row').forEach(r => {
    if (r.dataset.category === cat) r.classList.remove('hidden');
    else r.classList.add('hidden');
  });
  document.querySelectorAll('.detail-row').forEach(r => r.classList.add('hidden'));
  document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
  event.target.classList.add('active');
}
</script>
</body>
</html>`;
}

export function saveHtml(outputDir: string, runId: string, data: ReportData): string {
  const dir = path.resolve(outputDir);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const p = path.join(dir, `${runId}.html`);
  fs.writeFileSync(p, generateHtml(data), "utf-8");
  return p;
}
